name: test

on: [pull_request]

jobs:
    build:
        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                # TODO get tests working in Windows and Mac
                # windows-latest
                # macos-latest
                operating-system: [ubuntu-latest]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js latest
              uses: actions/setup-node@v3
              with:
                  node-version: latest
            - name: npm install, build, and test
              run: |
                  npm install
                  npm run build --if-present
                  npm run test:verbose
              env:
                  CI: true
